### ISSUE TITLE
onCreateOptionsMenu override

### ISSUE THREAD

**Issue by Mahdiazadbar** [alirezaafkar/Toolbar#2]
hi. thanks for this toolbar
how can i override onCreateOptionsMenu?
downt run OnCreatOptionMenu Code

**Comment by alirezaafkar** [comment]
@Mahdiazadbar 
Use **optionsMenu** attribute in xml 
_for example :_  app:optionsMenu="@menu/menu_main"

_or in Code:_
toolbar.inflateMenu(menu)

**Comment by Mahdiazadbar** [comment]
that right. but i like to use this style in my menu
http://stackoverflow.com/questions/17696486/actionbar-notification-count-badge-like-google-has
in need to onCreateOptionsMenu!!

**Comment by alirezaafkar** [comment]
@Mahdiazadbar 
You **can't** use _onCreateOptionsMenu_ with this toolbar!

For that style:

```
private void updateNotifCount(int count) {
        View badge = mToolbar.getMenu().findItem(R.id.badge).getActionView();
        notifCount = (Button) badge.findViewById(R.id.notif_count);
        notifCount.setText(String.valueOf(count));
}
```

and use **app:actionLayout** instead of _android:actionLayout_

**Comment by Mahdiazadbar** [comment]
thank your so much

**Comment by ghost** [comment]
I'm using MaterialIntroView library and I need to get view of a menu item. It seems it's possible only in onCreateOptionsMenu. But I can't set your custom toolbar as SupportActionBar. I will be thankful if you provide me a solution.
