### ISSUE TITLE
shadow for this toolbar

### ISSUE THREAD

**Issue by Mahdiazadbar** [alirezaafkar/Toolbar#3]
hi alireza, thanks for this toolbar.
how can set shadow for this toolbar. default android toolbar have a shadow
http://blog.grafixartist.com/wp-content/uploads/2015/06/Wordpress-2015-Header-Image.png

**Comment by alirezaafkar** [comment]
@Mahdiazadbar It has shadow!
But if you want to change the shadow size use this tags:

```
android:elevation="7dp"
tools:targetApi="lollipop" 
```
