### ISSUE TITLE
fiald to reslove

### ISSUE THREAD

**Issue by gh-darvishani** [alirezaafkar/Toolbar#5]
Hi alirezaa
i have this error when i put your code in dependencies
how i can fix  my problem 

![screenshot from 2016-06-02 18-47-59](https://cloud.githubusercontent.com/assets/5849044/15748044/94ccc134-28f2-11e6-9ff0-c4cd5edcc617.png)

**Comment by gh-darvishani** [comment]
What happened
Why is the issue closed

**Comment by alirezaafkar** [comment]
@masiha68 Because it is not related to this library,
You have to use VPN
