### ISSUE TITLE
use this lib with FlippedDrawerToggle

### ISSUE THREAD

**Issue by faezsghfi** [alirezaafkar/Toolbar#7]
I want use your lib in my app for supporting material design in pre 17 api  devices . so I add `FlippedDrawerToggle` to the toolbar because of its nice animation :) but it does not comfortable with this library and does not recognize it !! :((( can you help me? plz

**Comment by alirezaafkar** [comment]
Do you use custom libraries? Or the default one?

**Comment by alirezaafkar** [comment]
Added in new version.

**Comment by faezsghfi** [comment]
I LOVE you , my big savior ...
