### ISSUE TITLE
Using Toolbar with CollapsingToolbarLayout

### ISSUE THREAD

**Issue by RezaOruji** [alirezaafkar/Toolbar#8]
Hi Alireza,
Thank you for your great effort and great library, i am using it in almost all of my applications.
my question is that is it possible to use toolbar inside CollapsingToolbarLayout and use some collapsing effects like **pin** and **parallax** ?

**Comment by alirezaafkar** [comment]
Yes, It's possible.

**Comment by RezaOruji** [comment]
@alirezaafkar i tested it . it doesn't . i want to create it and add it to this library . i just need a starting point.
where should i start ?
